# AreportController.py
from AreportModel import ReportsModel
from PyQt6.QtWidgets import QMessageBox, QFileDialog
from datetime import datetime

# PDF Imports
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT


class ReportsController:
    def __init__(self, user_data=None):
        self.model = ReportsModel()
        self.view = None
        self.user_data = user_data
        self.current_report_data = []
        self.current_report_type = ""

    def set_view(self, view):
        self.view = view
        # Connect Signals
        self.view.generate_btn.clicked.connect(self.handle_generate_report)
        self.view.export_btn.clicked.connect(self.handle_export_report)

        # Initial Load: Show History
        self.load_report_history()

    def load_report_history(self):
        """Loads the list of previously generated reports"""
        try:
            reports = self.model.get_all_saved_reports()
            if self.view:
                self.view.load_reports(reports)
        except Exception as e:
            print(f"Error loading history: {e}")

    def handle_generate_report(self):
        """Fetch specific data based on dropdown selection and display it"""
        rtype = self.view.report_type.currentText()
        start = self.view.start_date.date().toString("yyyy-MM-dd")
        end = self.view.end_date.date().toString("yyyy-MM-dd")

        self.current_report_type = rtype
        data = []

        try:
            # Call specific model methods
            if rtype == "Stock Movement":
                data = self.model.get_stock_movement(start, end)
            elif rtype == "Inventory Status":
                data = self.model.get_inventory_status()
            elif rtype == "Defect Report":
                data = self.model.get_defective_report(start, end)
            elif rtype == "User Activity":
                data = self.model.get_user_activity(start, end)

            self.current_report_data = data
            self.view.display_report(data)

            # Save log entry
            user = self.user_data['username'] if self.user_data else "Admin"
            self.model.save_report_entry(rtype, start, end, user, transaction_id=None)
            self.load_report_history()

        except Exception as e:
            print(f"Report Generation Error: {e}")
            self.show_styled_message("Error", f"Failed to generate report: {e}", "Critical")

    def handle_export_report(self):
        if not self.current_report_data:
            self.show_styled_message("Error", "No data to export.", "Warning")
            return

        filename, _ = QFileDialog.getSaveFileName(
            self.view, "Save PDF", f"{self.current_report_type}_{datetime.now().strftime('%Y%m%d')}.pdf",
            "PDF Files (*.pdf)"
        )

        if filename:
            try:
                self.generate_pdf(filename)
                self.show_styled_message("Success", "Report exported successfully!", "Info")
            except Exception as e:
                self.show_styled_message("Error", f"Export failed: {e}", "Critical")

    def generate_pdf(self, filename):
        doc = SimpleDocTemplate(filename, pagesize=letter)
        elements = []
        styles = getSampleStyleSheet()

        # 1. Report Title
        title = Paragraph(f"PyesaTrak - {self.current_report_type}", styles['Title'])
        elements.append(title)
        elements.append(Spacer(1, 12))

        # 2. Metadata (Who generated it & When)
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Determine User Name (Full name preferred, fallback to username)
        if self.user_data:
            fname = self.user_data.get('userFname', '')
            lname = self.user_data.get('userLname', '')
            if fname or lname:
                user_str = f"{fname} {lname}".strip()
            else:
                user_str = self.user_data.get('username', 'Admin')
        else:
            user_str = "System Admin"

        # Create Metadata Block
        meta_style = styles['Normal']
        meta_style.fontSize = 10
        meta_style.textColor = colors.darkgray

        meta_text = f"""
        <b>Generated By:</b> {user_str}<br/>
        <b>Date Generated:</b> {date_str}<br/>
        """
        elements.append(Paragraph(meta_text, meta_style))
        elements.append(Spacer(1, 20))

        # 3. Table Data
        if not self.current_report_data:
            elements.append(Paragraph("No data available for this selection.", styles['Normal']))
        else:
            # Extract headers dynamically
            headers = [k.replace('_', ' ').title() for k in self.current_report_data[0].keys()]
            data_rows = [headers]

            for row in self.current_report_data:
                data_rows.append([str(val) for val in row.values()])

            # Table Styling
            t = Table(data_rows)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0076aa")),  # Teal Header
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))
            elements.append(t)

        doc.build(elements)

    def show_styled_message(self, title, text, icon_type):
        msg = QMessageBox(self.view)
        msg.setWindowTitle(title)
        msg.setText(text)
        if icon_type == "Info":
            msg.setIcon(QMessageBox.Icon.Information)
        elif icon_type == "Warning":
            msg.setIcon(QMessageBox.Icon.Warning)
        elif icon_type == "Critical":
            msg.setIcon(QMessageBox.Icon.Critical)
        msg.exec()